### ISSUE TITLE
Taking up too much of memory ram

### ISSUE THREAD

**Issue by oriolorra** [YeongHyeon/Skip-GANomaly#1]
Hello,

I have a problem while training. Every after epoch, it is taking up a bit of the memory ram.
Is there any way to solve this?

Thanks,

**Comment by YeongHyeon** [comment]
In my case, this source code does not consume much RAM and GPU resources.
I refer you to check another process is running together. 
If not you can adjust the source code on your desktop for minimizing RAM consumption as your need.
