### ISSUE TITLE
Abnormal classified as Normal

### ISSUE THREAD

**Issue by oriolorra** [YeongHyeon/Skip-GANomaly#2]
Hello,
I have trained the neural network with mnist dataset. 
Seems that the Encode-Decoder- Encoder reproduces well the normal class '1'. 

But when I do the test, a lot of abnormal classes are classified as normal, do you know why?

Thanks

**Comment by YeongHyeon** [comment]
Depending on what hyperparameter you used for learning, your results may differ from the README.
The result of README, which I provided, is that I used the specific hyperparameter that I found.
